import { Subject } from "@/types";

export const mockData: Subject[] = [
  {
    id: 1,
    name: "Introduction to Programming",
    code: "CSE101",
    description: "Basics of programming using C language",
    department: "CSE",
    createdAt: "2024-01-01T10:00:00Z",
  },
  {
    id: 2,
    name: "Data Structures",
    code: "CSE201",
    description: "Study of arrays, linked lists, stacks, and queues",
    department: "CSE",
    createdAt: "2024-01-05T10:00:00Z",
  },
  {
    id: 3,
    name: "Database Systems",
    code: "CSE301",
    description: "Relational databases and SQL fundamentals",
    department: "CSE",
    createdAt: "2024-01-10T10:00:00Z",
  },
  {
    id: 4,
    name: "Digital Logic Design",
    code: "EEE101",
    description: "Basic logic gates and digital circuits",
    department: "EEE",
    createdAt: "2024-01-12T10:00:00Z",
  },
  {
    id: 5,
    name: "Circuit Analysis",
    code: "EEE201",
    description: "Analysis of electrical circuits and networks",
    department: "EEE",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: 6,
    name: "Electromagnetics",
    code: "EEE301",
    description: "Electric and magnetic field theory",
    department: "EEE",
    createdAt: "2024-01-18T10:00:00Z",
  },
  {
    id: 7,
    name: "Thermodynamics",
    code: "ME101",
    description: "Basic laws of thermodynamics",
    department: "ME",
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: 8,
    name: "Fluid Mechanics",
    code: "ME201",
    description: "Behavior of fluids and flow analysis",
    department: "ME",
    createdAt: "2024-01-22T10:00:00Z",
  },
  {
    id: 9,
    name: "Machine Design",
    code: "ME301",
    description: "Design of mechanical components",
    department: "ME",
    createdAt: "2024-01-25T10:00:00Z",
  },
  {
    id: 10,
    name: "Engineering Mathematics",
    code: "MATH101",
    description: "Calculus and linear algebra basics",
    department: "Math",
    createdAt: "2024-01-28T10:00:00Z",
  },
  {
    id: 11,
    name: "Probability and Statistics",
    code: "MATH201",
    description: "Probability theory and statistical methods",
    department: "Math",
    createdAt: "2024-02-01T10:00:00Z",
  },
  {
    id: 12,
    name: "Probability and Statistics",
    code: "MATH201",
    description: "Probability theory and statistical methods",
    department: "Math",
    createdAt: "2024-02-01T10:00:00Z",
  },
  

  {
    id: 13,
    name: "Software Engineering",
    code: "CSE401",
    description: "Software development lifecycle and methodologies",
    department: "CSE",
    createdAt: "2024-02-05T10:00:00Z",
  },
  {
    id: 14,
    name: "Software Engineering",
    code: "CSE401",
    description: "Software development lifecycle and methodologies",
    department: "CSE",
    createdAt: "2024-02-05T10:00:00Z",
  },
];